swagger: "2.0"
info:
  description: "User cart manangement"
  version: "1.0.0"
  title: "Microservice user cart"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /cart/{user_id}:
    get:
      tags:
      - "cart view"
      summary: "get all cart products"
      description: "get user cart"
      operationId: "getCart"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "the user id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/cartItem" 
  /cart/{user_id}/add:
    post:
      tags:
      - "cart managment"
      summary: "add a product to user cart"
      description: ""
      operationId: "add2cart"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "the user id"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        description: "cart item"
        required: true
        schema:
            $ref: "#/definitions/cartItem"
      responses:
        "200":
          description: "successful operation"
  /cart/{user_id}/update:
    put:
      tags:
      - "cart managment"
      summary: "update user cart"
      description: ""
      operationId: "updateCart"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "the user id"
        required: true
        type: "integer"
      - name: "body"
        in: "body"
        description: "the user cart"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/cartItem"
      responses:
        "200":
          description: "successful operation"
          
definitions:
  cartItem:
    type: "object"
    properties:
      product_id:
        type: "integer"
      quantity:
        type: "integer"
      
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"