swagger: "2.0"
info:
  description: "services healthcheck manangement"
  version: "1.0.0"
  title: "Microservice healthcheck"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /HealthCheck:
    post:
      tags:
      - "HealthCheck"
      summary: "verify each services HealthCheck and send report"
      description: ""
      operationId: "add2cart"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                name: 
                  type: "string"
                  description: "service name"
                status:
                  type: "string"
                message:
                  type: "string"
      
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"