swagger: "2.0"
info:
  description: "products images manangement"
  version: "1.0.0"
  title: "Microservice Product Properties"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /images/{product_id}:
    get:
      tags:
      - "product Images"
      summary: "get a product images"
      description: "get Product Images by  product id"
      operationId: "getProductImagesByProductId"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        in: "path"
        description: "the product id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items: 
              $ref: "#/definitions/ProductImage"
  /images/{product_id}/main:
    get:
      tags:
      - "product Images"
      summary: "get a product main image"
      description: "get Product Main Image by  product id"
      operationId: "getProductMainImageByProductId"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        in: "path"
        description: "the product id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ProductImage"
  /properties/{product_id}/upload:
    post:
      tags:
      - "product Images"
      summary: "upload product image"
      description: ""
      operationId: "editProductProperties"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "product_id"
        in: "path"
        description: "product Id"
        required: true
        type: "integer"
      - name: "image"
        in: "formData"
        type: "string"
        description: "file contents"
      - name: "main"
        in: "formData"
        type: "boolean"
        description: "is main image"
          
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid message id supplied"
definitions:
  ProductImage:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uri:
        type: "string"
      value:
        type: "string"
      main:
        type: "boolean"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"