swagger: "2.0"
info:
  description: "Messages manangement"
  version: "1.0.0"
  title: "Swagger Users"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /message:
    post:
      tags:
      - "messages"
      summary: "Create message"
      description: "create a new message to a user"
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Message"
      responses:
        default:
          description: "successful operation"
  /messages/{userId}:
    get:
      tags:
      - "messages"
      summary: "get messages for a specific user"
      description: ""
      operationId: "getMessagesList"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "the user id"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items: 
              $ref: "#/definitions/MessageShort"
        "400":
          description: "Invalid message id supplied"
  /message/{id}:
    get:
      tags:
      - "messages"
      summary: "Get a message detail"
      description: ""
      operationId: "getMessageById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "message id to read"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Message"
        "400":
          description: "Invalid message id supplied"
definitions:
  MessageShort:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      from_user_id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
  Message:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
      contents:
        type: "string"
      from_user_id:
        type: "integer"
        format: "int64"
      to_user_id:
        type: "integer"
        format: "int64"
      date:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"