swagger: "2.0"
info:
  description: "Gestion des newsletters"
  version: "1.0.0"
  title: "Swagger Newsletter"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /subscribe:
    post:
      tags:
      - "newsletter"
      summary: "subscribe or unsubscribe to newsletter"
      description: "This can only be done by the logged in user."
      operationId: "newsletter"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "subscribe"
        description: "newsletter: true for subscribe, false for unsubscribe"
        required: true
        type: boolean
      responses:
        default:
          description: "successful operation"
  /get/{user_id}:
    get:
      tags:
      - "newsletter"
      summary: "newsletter status"
      description: "get newsletter status for a user"
      operationId: "loginUser"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "user_id"
        in: "path"
        description: "user login"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/subscription"
        "400":
          description: "Invalid user supplied"
definitions:
  subscription:
    type: "object"
    properties:
      isSubscribe:
        type: "integer"
        format: "int64"
      token:
        type: "string"
