version: '3.1'

services:
  db_server:
    image: mariadb:10.3
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=test-my-secret-pw
      - MYSQL_DATABASE=microservice
      - MYSQL_USER=microservice
      - MYSQL_PASSWORD=continuous
    volumes:
      - ./testing/testing.cnf:/etc/mysql/conf.d/testing.cnf:ro
    tmpfs: 
      - /var/lib/mysql:rw,noexec,nosuid,size=300m

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      environment:
       - PMA_ARBITRARY=1
      restart: always
      links:
        - db_server
      ports:
       - 8080:80
      volumes:
       - /sessions
      depends_on:
        - db_server