cache:
  paths:
    - vendor

stages:
  - build_stage
  - deploy_stage

build:
  image: php:7.3
  stage: build_stage
  only:
    - master
  script:
    - apt-get update -y
    - apt-get install -y gettext wget git zip unzip
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - php composer.phar  install --no-dev
    - envsubst < config.php.dist > config.php
    - mkdir build && cp -Rf . build/
  environment: 
    name: production
  artifacts:
    untracked: true
    paths:
      - build
      
deploy: 
  image: docker:latest
  stage: deploy_stage
  artifacts:
    untracked: true
  only:
    - tags
  script:
    - ls -lart build/
  environment: 
    name: production
  